# Compute Relative Power of EEG Bands

## Goals:
1. **Data Import**
    - Import the preprocessed data from npz and json files

2. **Feature Extraction**
    - Calculate the Power Spectral Density (PSD) for each epoch.
    - Average PSD values across all epochs 
    - Get AUC across freq values for each frequency band
    - Normalize AUC PSD values by computing the z-score for each
    
3. **Data Formatting**
    - Export the data as (1, 12, 6, 1, 16, 4)
        - (n_file, n_stimuli, (max)n_epochs, comfort_score, n_channels, n_bands)

# Import Libraries

In [1]:
import json
import numpy as np
import pandas as pd
import scipy.signal as signal
import matplotlib.pyplot as plt
import csv

# Custom libraries
from Functions import processing

# Import Epoched Data and Settings

In [2]:
# Load list of files to import
files = [  
    "sub-P007-Redo_ses-S001_task-T1_run-001_eeg",
    "sub-P008-Redo_ses-S001_task-T2_run-001_eeg"   
]

# Get unique subject IDs
subject_ids = [file.split('_')[0].split('sub-')[1] for file in files]

#spilt out the -Redo part of the subject IDs
subject_ids = [subj_id.split('-Redo')[0] for subj_id in subject_ids]

# Preallocate variables to store EEG data, settings, and comfort data
eeg_epochs = [None] * len(files)
settings = [None] * len(files)
comfort_data_dicts = [None] * len(files)

# Import data for each file
for f, file in enumerate(files):
    # Import EEG data, since it is stored in a compressed numpy file (.npz)
    loaded_data = np.load(f"Data\\Pilot-Data\\ML\\{file}.npz", allow_pickle=True)
    # Access the data for each stimulus
    eeg_epochs[f] = {stim_label: loaded_data[stim_label] for stim_label in loaded_data.files}
    
    # Import settings
    with open(f"Data\\Pilot-Data\\ML\\{file}.json", "r") as file_object:
        settings[f] = json.load(file_object)
    
    # Import comfort data"
    comfort_data = pd.read_csv(f"Data\\Pilot-Data\\ML\\{subject_ids[f]}-All-Comfort.csv") 
    grouped = comfort_data.groupby(["Contrast", "Size"])
    
    # Create a dictionary for this subject: keys like "ContrastXSizeY" map to lists of comfort values
    stim_comfort_dict = {}
    for (contrast, size), group in grouped:
        key = f"Contrast{contrast}Size{size}"
        values = group["Comfort_Score"].tolist()
        stim_comfort_dict[key] = values
        
    # Save the per-subject comfort dictionary for later processing
    comfort_data_dicts[f] = stim_comfort_dict

# Compute PSD for each "On" Epoch

- Calculate AUC for every channel for 4 freq bands
    - Do not include the SSVEP stim freqs/harmonics in the frequency bands

In [3]:
# PSD settings
window_size = 10  # For 10 second epochs: 10 = 0.1 Hz resolution, 5 = 0.2 Hz resolution, 2 = 0.5 Hz resolution

# Preallocate variables
eeg_f = [None] * len(files)
eeg_pxx = [None] * len(files)  

# Compute PSD for each file
for f in range(len(files)):
    eeg_f[f] = {}
    eeg_pxx[f] = {}

    for stim_label, epochs in eeg_epochs[f].items():  
        eeg_f[f][stim_label] = []
        eeg_pxx[f][stim_label] = []

        for epoch in epochs:  
            f_values, pxx_values = signal.welch(
                x=epoch,  
                fs=settings[f]["eeg_srate"],
                nperseg=window_size * settings[f]["eeg_srate"],
                noverlap=(window_size * settings[f]["eeg_srate"]) * 0.5,  
            )
            eeg_f[f][stim_label].append(f_values)
            eeg_pxx[f][stim_label].append(pxx_values)

        eeg_f[f][stim_label] = np.array(eeg_f[f][stim_label]) 
        eeg_pxx[f][stim_label] = np.array(eeg_pxx[f][stim_label]) 

# Define Frequency Bands
eeg_bands = {"delta": [1, 4], "theta": [4, 8], "alpha1": [8, 9], "alpha2": [11, 13], "beta1": [13, 19], "beta2": [21, 30]}

# Preallocate AUC array: (num_files, num_stimuli, max num_epochs, num_channels, num_bands)
auc = np.zeros((len(files), len(eeg_pxx[0]), 6, len(settings[f]['ch_names']), 4))

# Create a channel map to map new channel names to their indices in the full 16-channel layout and save for each file
chan_map = {}

for f in range(len(files)):
    new_ch_names = settings[f]['new_ch_names']

    # Create a mapping from new channel names to their indices in the full channel names, as a dict with channel names as keys
    full_ch_names = settings[f]['ch_names']
    chan_map[f] = {new_ch: full_ch_names.index(new_ch) for new_ch in new_ch_names if new_ch in full_ch_names}

    for stim_idx, stim_label in enumerate(eeg_pxx[f]):
        for epoch_idx in range(len(eeg_pxx[f][stim_label])):
            for band_idx, (band_name, band_range) in enumerate(eeg_bands.items()):
                fmask = (eeg_f[f][stim_label][0, :] >= band_range[0]) & (eeg_f[f][stim_label][0, :] <= band_range[1])
                
                # Integrate the PSD across the frequency range for each band
                if band_name == 'delta':
                    delta = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                    for i, ch_idx in enumerate(chan_map[f].values()):
                        auc[f, stim_idx, epoch_idx, ch_idx, 0] = delta[i]
                elif band_name == 'theta':
                    theta = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                    for i, ch_idx in enumerate(chan_map[f].values()):
                        auc[f, stim_idx, epoch_idx, ch_idx, 1] = theta[i]
                elif band_name == 'alpha1':
                    alpha1 = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                elif band_name == 'alpha2':
                    alpha2 = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                    full_alpha = alpha1 + alpha2
                    for i, ch_idx in enumerate(chan_map[f].values()):
                        auc[f, stim_idx, epoch_idx, ch_idx, 2] = full_alpha[i]
                elif band_name == 'beta1':
                    beta1 = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                elif band_name == 'beta2':
                    beta2 = np.trapezoid(eeg_pxx[f][stim_label][epoch_idx][:, fmask], x=eeg_f[f][stim_label][0, fmask], axis=1)
                    full_beta = beta1 + beta2
                    for i, ch_idx in enumerate(chan_map[f].values()):
                        auc[f, stim_idx, epoch_idx, ch_idx, 3] = full_beta[i]

# Print shape of the final AUC array
print(f"AUC: {auc.shape}") # (num_files, num_stimuli, max(num_epochs), num_channels, num_bands)

AUC: (2, 12, 6, 16, 4)


# Normalize the AUC values
- Z-score
    * First reshape so all values are one long list for each participant 
        - $(1,\ 12 \times 6 \times 16 \times 4)$ for 1 file, 12 stimuli, 6 epochs, 16 channels, 4 frequency bands
    * Compute the mean and std for all AUC PSD values, excluding the zero values (from bad channels)
        - mean/std of 4,608 values (minus bads) for above example
    * Reshape the mean/std arrays so they can be combined with the original auc array
    * Calculate the z-score for each AUC PSD value
        * **Formula**:  $
\text{PSD Z-score} = \frac{\text{AUC PSD}_{\text{single channel/band}} - \mu_{\text{baseline}}}{\sigma_{\text{baseline}}}
$


In [4]:
# Flatten each file's data: (num_files, -1)
auc_reshaped = auc.reshape(auc.shape[0], -1)

# Create a mask for non-zero values
nonzero_mask = auc_reshaped != 0

# Compute mean/std excluding zeros
means = np.sum(auc_reshaped * nonzero_mask, axis=1, keepdims=True) / np.sum(nonzero_mask, axis=1, keepdims=True)
stds = np.sqrt(np.sum(((auc_reshaped - means)**2) * nonzero_mask, axis=1, keepdims=True) / np.sum(nonzero_mask, axis=1, keepdims=True))

# Avoid divide-by-zero
stds[stds == 0] = 1

# Compute z-scores and add 0 values back in
auc_normalized_flat = (auc_reshaped - means) / stds
auc_normalized_flat[~nonzero_mask] = 0

# Reshape back to original
auc_normalized = auc_normalized_flat.reshape(*auc.shape)

# Print shape of the normalized AUC array
print(f"Normalized AUC: {auc_normalized.shape}")  # (num_files, num_stimuli, max(num_epochs), num_channels, num_bands)

Normalized AUC: (2, 12, 6, 16, 4)


# Combine stimuli, comfort scores, and PSD (per freq band)

Shape will be (n_file, n_stimuli, (max)n_epochs, comfort_score, n_channels, n_bands)
- for each stim it will be arr[f , stim] = (6, 1, 16, 4)

In [ ]:
# Preallocate array with the given shape
ml_input = np.zeros((
    len(files),                        # Number of files
    len(eeg_pxx[0]),                   # Number of stimuli
    6,                                 # Max Number of Epochs
    1,                                 # Number of comfort scores per stimulus
    len(settings[f]['ch_names']),  # Number of channels
    4                                  # Number of bands
))  

eeg_bands = {"delta": [1, 4], "theta": [4, 8], "alpha": [8, 9], "beta": [13, 19]}

for f in range(len(files)):
    for stim_idx, stim_label in enumerate(eeg_pxx[f]):
        for epoch_idx in range(len(eeg_pxx[f][stim_label])):
            for comfort_idx, (c_stim_label, comfort_score) in enumerate(comfort_data_dicts[f].items()):
                if stim_label == c_stim_label:
                    # Get the specific comfort score for this epoch
                    comfort_value = comfort_score[epoch_idx]

                    for band_idx, (band_name, band_range) in enumerate(eeg_bands.items()):
                            # Assign the AUC value to the ml_input array
                            if band_name == 'delta':
                                ml_input[f, stim_idx, epoch_idx, 0, :, 0] = auc_normalized[f, stim_idx, epoch_idx, :, 0]
                            elif band_name == 'theta':
                                ml_input[f, stim_idx, epoch_idx, 0, :, 1] = auc_normalized[f, stim_idx, epoch_idx, :, 1]
                            elif band_name == 'alpha':
                                ml_input[f, stim_idx, epoch_idx, 0, :, 2] = auc_normalized[f, stim_idx, epoch_idx, :, 2]
                            elif band_name == 'beta':
                                ml_input[f, stim_idx, epoch_idx, 0, :, 3] = auc_normalized[f, stim_idx, epoch_idx, :, 3]

# Print shape of the ml_input array
print(f"ml_input: {ml_input.shape}")    # (num_files, num_stimuli, max(num_epochs), comfort_score(n = 1), num_channels, num_bands)

ml_input: (2, 12, 6, 1, 16, 4)
[[ 5.06315393e-01 -2.73564294e-02 -3.57533751e-01 -2.34704789e-01]
 [ 3.52252610e-01 -1.64908720e-01 -3.86831015e-01 -2.80802322e-01]
 [ 3.43553536e-01 -2.24726961e-01 -4.22904281e-01 -2.83960376e-01]
 [ 1.16471595e-01 -1.87766282e-02 -2.86529120e-01 -1.78185576e-01]
 [ 1.00915487e-01 -1.31869841e-02 -2.99970139e-01 -1.56245134e-01]
 [-2.08667246e-04 -1.27747774e-01 -2.54685048e-01 -1.32058890e-01]
 [-1.68389463e-01 -3.63241657e-01 -3.96035498e-01 -3.05356775e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.53344376e-01 -2.94517720e-02 -1.78562305e-01  3.37839233e-01]
 [-8.59818043e-02 -1.36806745e-01 -2.85143879e-01  3.90232558e-01]
 [-2.14836118e-01 -1.55198911e-01 -3.41571896e-01 -1.94187758e-02]
 [-2.22892741e-01 -2.54795175e-01 -3.46612943e-01  1.27761900e-01]
 [-2.42065996e-01 -2.58898816e-01 -3.79369680e-01 -1.47568508e-01]
 [-2.42073210e-01 -3.08953283e-

# Save ML Input to CSV (individual)

In [6]:
# Define the EEG bands and channel names
eeg_bands = {"delta": [1, 4], "theta": [4, 8], "alpha": [8, 9], "beta": [13, 19]}
ch_names = ["Fz", "F4", "F8", "C3", "Cz", "C4", "T8", "P7", "P3", "P4", "P8", "PO7", "PO8", "O1", "Oz", "O2"]
chan_map_full = {ch: idx for idx, ch in enumerate(ch_names)}

# Define the structure for the CSV header
eeg_band_columns = [
    f"{ch}_{band}" for ch in settings[f]['ch_names'] for band in eeg_bands.keys()
]
header = ['Participant', 'Stimulus', 'Epoch', 'Comfort Score'] + eeg_band_columns

# Open the CSV file for writing
with open('Data\\Pilot-Data\\ML\\combined_ml_input.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)
    
    # Iterate through the ml_input data
    for f in range(len(files)):
        # Extract participant ID from filename
        participant_id = subject_ids[f]

        for stim_idx, stim_label in enumerate(eeg_pxx[f]):
            for epoch_idx in range(len(eeg_pxx[f][stim_label])):
                for comfort_idx, (c_stim_label, comfort_score) in enumerate(comfort_data_dicts[f].items()):
                    if stim_label == c_stim_label:
                        comfort_value = comfort_score[epoch_idx]
                        
                        row = [participant_id, stim_label, epoch_idx, comfort_value]
                        
                        channel_band_data = {f"{ch}_{band}": 0 for ch in ch_names for band in eeg_bands.keys()}
                        
                        for ch_idx, ch_name in enumerate(chan_map_full.items()):
                            for band_idx, (band_name, band_range) in enumerate(eeg_bands.items()):
                                if ch_name[0] in ch_names:
                                    band_value = ml_input[f, stim_idx, epoch_idx, 0, ch_idx, band_idx]
                                    channel_band_data[f"{ch_name[0]}_{band_name}"] = band_value
                                            
                        for ch_band in eeg_band_columns:
                            row.append(channel_band_data[ch_band])
                                
                        writer.writerow(row)

print("Data successfully written to ml_input_output.csv")

Data successfully written to ml_input_output.csv
